apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  lables:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx


'''

apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env:
       - name: POSTGRES_PASSWORD
         value: mysecretpassword
'''